### ISSUE TITLE
Error: spawn Unknown system errno 12

### ISSUE THREAD

**Issue by kaihendry** [remy/eventsource-h5d#2]
I've been running the example and I get these sorts of errors after a while.

localhost:~/eventsource-h5d$ sudo node app.js  
Listening on port 80

child_process.js:470
    throw errnoException(errno, 'spawn');
    ^
Error: spawn Unknown system errno 12
    at errnoException (child_process.js:507:11)
    at ChildProcess.spawn (child_process.js:470:11)
    at child_process.js:367:9
    at Object.execFile (child_process.js:277:15)
    at child_process.js:244:18
    at Object.uptime [as _onTimeout](/home/hendry/eventsource-h5d/app.js:11:15)
    at Timer.ontimeout (timers.js:84:39)

**Comment by bmeck** [comment]
This is an ENOMEM, so presumably a memory leak is happening, do you have stats around when this occurs of memory usage?
